# Generated by Django 5.2.15 on 2026-08-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageryservice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('validating', 'Validating'), ('preparing', 'Preparing'), ('publishing', 'Publishing'), ('online', 'Online'), ('degraded', 'Degraded'), ('offline', 'Offline'), ('failed', 'Failed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='servicepublishjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
