# Generated by Django 5.2.15 on 2026-08-24 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageryRecord',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('scene_key', models.CharField(max_length=255, unique=True)),
                ('identity_hash', models.CharField(max_length=64, unique=True)),
                ('stac_id', models.CharField(max_length=255, unique=True)),
                ('source_name', models.CharField(max_length=512)),
                ('platform_code', models.CharField(blank=True, max_length=80)),
                ('satellite_name', models.CharField(blank=True, max_length=255)),
                ('sensor', models.CharField(blank=True, max_length=120)),
                ('imaging_mode', models.CharField(blank=True, max_length=120)),
                ('imaging_mode_detail', models.CharField(blank=True, max_length=120)),
                ('polarization', models.CharField(blank=True, max_length=40)),
                ('polarizations', models.JSONField(blank=True, default=list)),
                ('product_level', models.CharField(blank=True, max_length=40)),
                ('acquisition_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('acquisition_start', models.DateTimeField(blank=True, null=True)),
                ('acquisition_end', models.DateTimeField(blank=True, null=True)),
                ('time_assumption', models.CharField(blank=True, max_length=80)),
                ('orbit_id', models.CharField(blank=True, max_length=80)),
                ('orbit_direction', models.CharField(blank=True, max_length=40)),
                ('look_side', models.CharField(blank=True, max_length=40)),
                ('resolution_m', models.FloatField(blank=True, null=True)),
                ('pixel_spacing_range_m', models.FloatField(blank=True, null=True)),
                ('pixel_spacing_azimuth_m', models.FloatField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('incidence_angle_near_deg', models.FloatField(blank=True, null=True)),
                ('incidence_angle_far_deg', models.FloatField(blank=True, null=True)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('epsg', models.IntegerField(blank=True, null=True)),
                ('metadata_status', models.CharField(default='partial', max_length=30)),
                ('spatial_status', models.CharField(default='partial', max_length=30)),
                ('preview_status', models.CharField(default='missing', max_length=30)),
                ('metadata_sources', models.JSONField(blank=True, default=list)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('stac_path', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('partial', 'Partial'), ('broken', 'Broken')], default='partial', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_uploaded_imagery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acquisition_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageryProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagery_tags', to='projects.project')),
                ('imagery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tags', to='imagery.imageryrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ImageryAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('data', 'Data'), ('preview', 'Preview'), ('thumbnail', 'Thumbnail'), ('metadata', 'Metadata'), ('incidence', 'Incidence'), ('log', 'Log')], max_length=20)),
                ('name', models.CharField(max_length=512)),
                ('path', models.TextField()),
                ('media_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imagery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='imagery.imageryrecord')),
            ],
        ),
        migrations.AddIndex(
            model_name='imageryrecord',
            index=models.Index(fields=['platform_code', 'imaging_mode'], name='imagery_ima_platfor_f30404_idx'),
        ),
        migrations.AddIndex(
            model_name='imageryrecord',
            index=models.Index(fields=['polarization', 'product_level'], name='imagery_ima_polariz_aa6ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='imageryrecord',
            index=models.Index(fields=['metadata_status', 'preview_status'], name='imagery_ima_metadat_767155_idx'),
        ),
        migrations.AddConstraint(
            model_name='imageryprojecttag',
            constraint=models.UniqueConstraint(fields=('imagery', 'project'), name='unique_imagery_project_tag'),
        ),
        migrations.AddConstraint(
            model_name='imageryasset',
            constraint=models.UniqueConstraint(fields=('imagery', 'role'), name='unique_imagery_asset_role'),
        ),
    ]
