# Generated by Django 5.2.15 on 2026-08-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageryrecord',
            name='archive_filename',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='imageryrecord',
            name='archive_job_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
