# Generated by Django 5.2.15 on 2026-08-25 08:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagery', '0002_imageryrecord_archive_filename_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imageryrecord',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageryrecord',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_imagery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imageryrecord',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imageryrecord',
            name='display_name',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='imageryrecord',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='ImageryDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imagery_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageryDatasetMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_imagery_dataset_members', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='imagery.imagerydataset')),
                ('imagery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dataset_memberships', to='imagery.imageryrecord')),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['dataset', 'position'], name='imagery_ima_dataset_d5d5aa_idx')],
                'constraints': [models.UniqueConstraint(fields=('dataset', 'imagery'), name='unique_dataset_imagery')],
            },
        ),
    ]
