# Generated by Django 5.2.15 on 2026-08-25 09:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagery', '0003_imageryrecord_archived_at_imageryrecord_archived_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerydataset',
            name='last_refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagerydataset',
            name='membership_type',
            field=models.CharField(choices=[('static', 'Static'), ('query', 'Query')], default='static', max_length=20),
        ),
        migrations.AddField(
            model_name='imagerydataset',
            name='query_definition',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='imagerydataset',
            name='refresh_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('on_ingestion', 'On ingestion')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='ImagerySavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('query_definition', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imagery_saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
