# Generated by Django 5.2.15 on 2026-08-25 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagery', '0004_imagerydataset_last_refreshed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imageryrecord',
            name='cog_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imageryrecord',
            name='cog_path',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imageryrecord',
            name='cog_status',
            field=models.CharField(choices=[('none', 'Not generated'), ('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('stale', 'Stale')], db_index=True, default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='imageryrecord',
            name='cog_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='imageryrecord',
            index=models.Index(fields=['cog_status', 'is_archived'], name='imagery_ima_cog_sta_7c37f9_idx'),
        ),
    ]
