# Generated by Django 5.2.15 on 2026-09-03 03:58

from django.db import migrations, models


def backfill_public(apps, schema_editor):
    """Existing data was visible to everyone before visibility existed;
    keep that behavior after the upgrade by marking it public."""
    ImageryRecord = apps.get_model("imagery", "ImageryRecord")
    ImageryDataset = apps.get_model("imagery", "ImageryDataset")
    ImageryRecord.objects.filter(visibility="private").update(visibility="public")
    ImageryDataset.objects.filter(visibility="private").update(visibility="public")


def no_op(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('imagery', '0006_imageryasset_access_mode_imageryasset_storage_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerydataset',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], db_index=True, default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='imageryrecord',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], db_index=True, default='private', max_length=10),
        ),
        migrations.RunPython(backfill_public, no_op),
    ]
