# Generated by Django 5.2.15 on 2026-08-25 14:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('frozen', 'Frozen'), ('archived', 'Archived')], db_index=True, default='frozen', max_length=20)),
                ('imagery_ids', models.JSONField(default=list)),
                ('manifest', models.JSONField(default=dict)),
                ('frozen_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-frozen_at'],
            },
        ),
        migrations.AddField(
            model_name='exportjob',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exports', to='delivery.deliverysnapshot'),
        ),
    ]
