# Generated by Django 5.2.15 on 2026-08-24 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagery', '0001_initial'),
        ('ingestion', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionitem',
            name='container',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingestionitem',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_ingestion_items', to='imagery.imageryrecord'),
        ),
        migrations.AddField(
            model_name='ingestionitem',
            name='metadata_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ingestionitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ingestion.ingestionitem'),
        ),
        migrations.AddField(
            model_name='ingestionitem',
            name='relative_path',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ingestionitem',
            name='scene_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='warning_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingestionitem',
            name='source_kind',
            field=models.CharField(choices=[('url', 'URL'), ('archive_member', 'Archive member'), ('file', 'File'), ('folder_file', 'Folder file')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ingestionitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('extracting', 'Extracting'), ('scanning', 'Scanning'), ('parsing', 'Parsing'), ('storing', 'Storing'), ('done', 'Done'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingestionjob',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_jobs', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='ingestionjob',
            name='source_type',
            field=models.CharField(choices=[('url_text', 'URL text'), ('zip_upload', 'ZIP upload'), ('archive_upload', 'Archive upload'), ('folder_zip', 'Folder ZIP'), ('folder_upload', 'Folder upload')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ingestionjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('validating', 'Validating'), ('running', 'Running'), ('scanning', 'Scanning'), ('parsing', 'Parsing'), ('storing', 'Storing'), ('done', 'Done'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
