# Generated by Django 5.2.15 on 2026-08-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_ingestionitem_container_ingestionitem_duplicate_of_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionjob',
            name='source_type',
            field=models.CharField(choices=[('url_text', 'URL text'), ('zip_upload', 'ZIP upload'), ('archive_upload', 'Archive upload'), ('folder_zip', 'Folder ZIP'), ('folder_upload', 'Folder upload'), ('storage_reference', 'Storage reference')], max_length=20),
        ),
    ]
